linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  gocritic:
    enabled-tags:
      - performance
  gosec:
    excludes:
      - G104
