// Code generated by "{{ .RepoName }}"; DO NOT EDIT.

package {{ .PackageName }}_test

import (
	"fmt"
	"os"
	"testing"

	"github.com/mvrahden/go-test/cmd/autotestgen"
)

func TestMain(m *testing.M) {
	err := autotestgen.Generate() // auto-generate before running all tests
	if err != nil {
		fmt.Printf("failed generating test suite: %s\n", err)
		os.Exit(1)
	}

	os.Exit(m.Run())
}