package testgen_test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mvrahden/go-test/internal/cmd/testgen"
	"github.com/stretchr/testify/require"
)

func TestE2E_CLI(t *testing.T) {
	testgen.PatchDeleteOldGeneratedFileFunc(t)

	testcases := []struct {
		desc                   string
		dirName                string
		goldenFile             string
		args                   []string
		expectedOutputFilename string
		expectedAutogenFile    bool
	}{
		{"no args", "testsuite", "gotest.golden", nil, "gotest_gensuite_test.go", true},
		{"define out file", "testsuite", "gotest.golden", []string{"-out=gotest_gensuite_test.abc.go"}, "gotest_gensuite_test.abc.go", true},
		{"define out file", "testsuite", "gotest.golden", []string{"-out=gotest_gensuite_test.abc.go", "-skip-autogen"}, "gotest_gensuite_test.abc.go", false},
	}
	for idx, tC := range testcases {
		t.Run(fmt.Sprintf("Generate (idx: %d %q)", idx, tC.desc), func(t *testing.T) {

			tmpDir := t.TempDir()
			testgen.PatchTargetFilenameFunc(t, tmpDir)
			tmpFile := filepath.Join(tmpDir, tC.expectedOutputFilename)

			args := []string{
				"-dir=" + filepath.Join("testdata", tC.dirName)}
			args = append(args, tC.args...)
			err := testgen.Execute(args)
			require.NoError(t, err)

			// Assert generate suite
			require.FileExists(t, tmpFile)

			actual, err := os.ReadFile(tmpFile)
			require.NoError(t, err)
			expected, err := os.ReadFile(filepath.Join("testdata", tC.dirName, tC.goldenFile))
			require.NoError(t, err)
			require.Equal(t, string(expected), string(actual))

			// Assert generated autogen file
			tmpAutogenFile := filepath.Join(tmpDir, "gotest_autogen_test.go")
			if !tC.expectedAutogenFile {
				require.NoFileExists(t, tmpAutogenFile)
				return
			}
			require.FileExists(t, tmpAutogenFile)
			buf, err := os.ReadFile(tmpAutogenFile)
			require.NoError(t, err)
			require.True(t,
				strings.HasPrefix(string(buf),
					`// Code generated by "go-test (github.com/mvrahden/go-test)"; DO NOT EDIT.

package e2epkg_test`),
				"should have correct gen comment and package: %s", buf)
		})
	}
}

func TestE2E_Errors(t *testing.T) {
	testcases := []struct {
		desc string
		args []string
		msg  string
	}{
		{
			"on no enums in given directory (wrong path)", []string{"-dir=testdata/nothing-here"}, "no such directory",
		},
	}
	for _, tC := range testcases {
		t.Run(tC.desc, func(t *testing.T) {
			err := testgen.Execute(tC.args)
			require.ErrorContains(t, err, tC.msg)
		})
	}
}
