// Code generated by "go-test (github.com/mvrahden/go-test)"; DO NOT EDIT.

package focussuite_test

import (
	"fmt"
	"os"
	"testing"

	"github.com/mvrahden/go-test/cmd/gotestgen"
)

func TestMain(m *testing.M) {
	err := gotestgen.Generate() // auto-generate before running all tests
	if err != nil {
		fmt.Printf("failed generating test harness: %s\n", err)
		os.Exit(1)
	}

	os.Exit(m.Run())
}
