// Code generated by "go-test (github.com/mvrahden/go-test)"; DO NOT EDIT.

package focussuite_test

import (
	"testing"

	"github.com/mvrahden/go-test/examples/focus_suite"
)

func Test_F_FocusedTestSuite(t *testing.T) {
	_ = F_FocusedTestSuite{}
}

func Test__F_FocusedTestSuite(t *testing.T) {
	_ = focussuite.F_FocusedTestSuite{}
}

func Test_X_ExcludedTestSuite(t *testing.T) {
	t.Skipf("test suite was excluded by user")
}

func Test__X_ExcludedTestSuite(t *testing.T) {
	t.Skipf("test suite was excluded by user")
}

func Test_NoopTestSuite(t *testing.T) {
	t.Skipf("test suite was excluded by user")
}

func Test__NoopTestSuite(t *testing.T) {
	t.Skipf("test suite was excluded by user")
}
