package gotestgen

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"testing"

	"github.com/stretchr/testify/require"
)

var (
	IS_GEN_FILE = regexp.MustCompile(`^// Code generated by "go-test \(github\.com\/mvrahden\/go-test\)"; DO NOT EDIT\.(?:$|\n)`)
)

func TestGeneratorGoldenExamples(t *testing.T) {
	goWorkFile := filepath.Join("..", "..", "go.work")
	if _, err := os.Stat(goWorkFile); os.IsNotExist(err) {
		t.Skip("go.work not found — run 'go work init . && go work use ./examples' at the project root to enable cross-module golden tests")
	}

	for _, tC := range []struct {
		directory   string
		pkgName     string
		description string
	}{
		{"stdlib", "github.com/mvrahden/go-test/examples/stdlib", "stdlib and testsuites"},
		{"simple_suite", "github.com/mvrahden/go-test/examples/simple_suite", "simple test suites"},
		{"focus_exclude", "github.com/mvrahden/go-test/examples/focus_exclude", "focus and exclude semantics"},
		{"parallel_suite", "github.com/mvrahden/go-test/examples/parallel_suite", "parallel test suites"},
	} {
		pkg := path.Join("..", "..", "examples", tC.directory)
		testdatadir := filepath.Join("..", "..", "examples", tC.directory, "testdata")

		t.Run(fmt.Sprintf("Generate for package %q with %s", tC.directory, tC.description), func(t *testing.T) {
			res, err := Generate(pkg)
			require.NoError(t, err)
			require.NotEmpty(t, res, "expected non-empty results for %s", tC.directory)
			for _, v := range res {
				require.Equal(t, tC.pkgName, v.Package)
				require.NotEqual(t, tC.pkgName, v.AbsPath)
				require.NotZero(t, v.AbsPath)
				require.True(t, filepath.IsAbs(v.AbsPath))
				ptestExpected := getExpectedOutputFile(t, testdatadir, "gotestgen_ptest.golden")
				require.Equal(t, ptestExpected, string(v.PTest))
				pxtestExpected := getExpectedOutputFile(t, testdatadir, "gotestgen_pxtest.golden")
				require.Equal(t, pxtestExpected, string(v.PXTest))
			}
		})
	}
}

func getExpectedOutputFile(t *testing.T, testdatadir, fileName string) string {
	f, err := os.Open(filepath.Join(testdatadir, fileName))
	require.NoError(t, err)
	defer f.Close()

	buf, err := io.ReadAll(f)
	require.NoError(t, err)
	els := bytes.SplitN(buf, []byte("\n"), 2)
	require.Len(t, els, 2)
	firstLine := els[0]
	require.True(t, IS_GEN_FILE.Match(firstLine), "Must be a generated file!")
	return string(buf)
}
