package gotestgen

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"testing"

	"github.com/mvrahden/go-test/pkg/gotest"
)

var (
	IS_GEN_FILE = regexp.MustCompile(`^// Code generated by "gotest \(github\.com\/mvrahden\/go-test\)"; DO NOT EDIT\.(?:$|\n)`)
)

func TestGeneratorGoldenExamples(t *testing.T) {
	goWorkFile := filepath.Join("..", "..", "go.work")
	if _, err := os.Stat(goWorkFile); os.IsNotExist(err) {
		t.Skip("go.work not found — run 'go work init . && go work use ./examples' at the project root to enable cross-module golden tests")
	}

	for _, tC := range []struct {
		directory   string
		pkgName     string
		description string
	}{
		{"auth", "github.com/mvrahden/go-test/examples/auth", "auth validator suites"},
		{"cart", "github.com/mvrahden/go-test/examples/cart", "shopping cart suites"},
		{"search", "github.com/mvrahden/go-test/examples/search", "parallel search suites with generics"},
	} {
		pkg := path.Join("..", "..", "examples", tC.directory)
		testdatadir := filepath.Join("..", "..", "examples", tC.directory, "testdata")

		t.Run(fmt.Sprintf("Generate for package %q with %s", tC.directory, tC.description), func(t *testing.T) {
			loaded, err := LoadPackages([]string{pkg}, nil)
			gotest.NoError(t, err)
			res, _, err := GenerateFromLoaded(loaded)
			gotest.NoError(t, err)
			gotest.NotEmpty(t, res, "expected non-empty results for %s", tC.directory)
			for _, v := range res {
				gotest.Equal(t, tC.pkgName, v.PkgPath)
				gotest.NotEqual(t, tC.pkgName, v.AbsPath)
				gotest.NotZero(t, v.AbsPath)
				gotest.True(t, filepath.IsAbs(v.AbsPath))
				ptestExpected := getExpectedOutputFile(t, testdatadir, "gotestgen_ptest.golden")
				gotest.Equal(t, ptestExpected, string(v.PTest))
				pxtestExpected := getExpectedOutputFile(t, testdatadir, "gotestgen_pxtest.golden")
				gotest.Equal(t, pxtestExpected, string(v.PXTest))
			}
		})
	}
}

func TestGeneratorGoldenExamples_DumpGolden(t *testing.T) {
	if os.Getenv("DUMP_GOLDEN") != "1" {
		t.Skip("set DUMP_GOLDEN=1 to regenerate golden files")
	}

	for _, tC := range []struct {
		directory string
	}{
		{"auth"},
		{"cart"},
		{"search"},
	} {
		pkg := path.Join("..", "..", "examples", tC.directory)
		testdatadir := filepath.Join("..", "..", "examples", tC.directory, "testdata")

		loaded, err := LoadPackages([]string{pkg}, nil)
		if err != nil {
			t.Fatalf("LoadPackages %s: %v", tC.directory, err)
		}
		res, _, err := GenerateFromLoaded(loaded)
		if err != nil {
			t.Fatalf("GenerateFromLoaded %s: %v", tC.directory, err)
		}
		for _, v := range res {
			if len(v.PTest) > 0 {
				os.WriteFile(filepath.Join(testdatadir, "gotestgen_ptest.golden"), v.PTest, 0644)
				fmt.Fprintf(os.Stderr, "wrote %s/gotestgen_ptest.golden\n", testdatadir)
			}
			if len(v.PXTest) > 0 {
				os.WriteFile(filepath.Join(testdatadir, "gotestgen_pxtest.golden"), v.PXTest, 0644)
				fmt.Fprintf(os.Stderr, "wrote %s/gotestgen_pxtest.golden\n", testdatadir)
			}
		}
	}
	t.Log("Golden files regenerated. Re-run TestGeneratorGoldenExamples to verify.")
}

func TestGenerate_StdlibPackage_ReturnsEmpty(t *testing.T) {
	loaded, err := LoadPackages([]string{"strings"}, nil)
	gotest.NoError(t, err)
	gotest.Empty(t, loaded)
}

func getExpectedOutputFile(t *testing.T, testdatadir, fileName string) string {
	f, err := os.Open(filepath.Join(testdatadir, fileName))
	gotest.NoError(t, err)
	defer f.Close()

	buf, err := io.ReadAll(f)
	gotest.NoError(t, err)
	els := bytes.SplitN(buf, []byte("\n"), 2)
	gotest.Len(t, els, 2)
	firstLine := els[0]
	gotest.True(t, IS_GEN_FILE.Match(firstLine), "Must be a generated file!")
	return string(buf)
}
