package gotestgen_test

import (
	"bytes"
	"io"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/mvrahden/go-test/internal/gotestgen"
	"github.com/mvrahden/go-test/pkg/gotest"
)

var (
	IS_GEN_FILE = regexp.MustCompile(`^// Code generated by "gotest \(github\.com\/mvrahden\/go-test\)"; DO NOT EDIT\.(?:$|\n)`)
)

type GeneratorTestSuite struct{}

func (s *GeneratorTestSuite) TestGoldenExamples(t *gotest.T) {
	t.When("cross-module golden tests", func(w *gotest.T) {
		goWorkFile := filepath.Join("..", "..", "go.work")
		if _, err := os.Stat(goWorkFile); os.IsNotExist(err) {
			w.It("skips when go.work is missing", func(it *gotest.T) {
				it.T().Skip("go.work not found — run 'go work init . && go work use ./examples' at the project root to enable cross-module golden tests")
			})
			return
		}

		for _, tC := range []struct {
			directory   string
			pkgName     string
			description string
		}{
			{"auth", "github.com/mvrahden/go-test/examples/auth", "auth validator suites"},
			{"cart", "github.com/mvrahden/go-test/examples/cart", "shopping cart suites"},
			{"search", "github.com/mvrahden/go-test/examples/search", "parallel search suites with generics"},
		} {
			w.It("generates correct output for "+tC.directory, func(it *gotest.T) {
				pkg := path.Join("..", "..", "examples", tC.directory)

				loaded, err := gotestgen.LoadPackages([]string{pkg}, nil)
				gotest.NoError(it, err)
				res, _, err := gotestgen.GenerateFromLoaded(loaded)
				gotest.NoError(it, err)
				gotest.NotEmpty(it, res, "expected non-empty results for %s", tC.directory)
				for _, v := range res {
					gotest.Equal(it, tC.pkgName, v.PkgPath)
					gotest.NotEqual(it, tC.pkgName, v.AbsPath)
					gotest.NotZero(it, v.AbsPath)
					gotest.True(it, filepath.IsAbs(v.AbsPath))
					gotest.MatchSnapshot(it, string(v.PTest), tC.directory+"-ptest")
					gotest.MatchSnapshot(it, string(v.PXTest), tC.directory+"-pxtest")
				}
			})
		}
	})
}

func (s *GeneratorTestSuite) TestStdlibPackageReturnsEmpty(t *gotest.T) {
	t.When("loading a stdlib package", func(w *gotest.T) {
		w.It("returns empty results", func(it *gotest.T) {
			loaded, err := gotestgen.LoadPackages([]string{"strings"}, nil)
			gotest.NoError(it, err)
			gotest.Empty(it, loaded)
		})
	})
}

// --- E2E tests (folded from generator_e2e_test.go) ---

func (s *GeneratorTestSuite) TestE2ECLI(t *gotest.T) {
	t.When("CLI-level generation", func(w *gotest.T) {
		for _, tC := range []struct {
			desc    string
			dirName string
			hasPX   bool
		}{
			{"no testsuite", "no_testsuite", true},
			{"simple testsuite", "testsuite", true},
			{"suite guard", "suite_guard", false},
			{"fixture lifecycle", "fixture_lifecycle", false},
		} {
			w.It("generates correct output for "+tC.desc, func(it *gotest.T) {
				cwd, err := os.Getwd()
				gotest.NoError(it, err)

				dirPath := filepath.Join(cwd, "testdata_e2e", tC.dirName)
				loaded, err := gotestgen.LoadPackages([]string{dirPath}, nil)
				gotest.NoError(it, err)
				results, _, err := gotestgen.GenerateFromLoaded(loaded)
				gotest.NoError(it, err)
				gotest.True(it, strings.HasSuffix(results[0].AbsPath, "go-test/internal/gotestgen/testdata_e2e/"+tC.dirName))
				gotest.Equal(it, "github.com/mvrahden/go-test/internal/gotestgen/testdata_e2e/"+tC.dirName, results[0].PkgPath)

				gotest.MatchSnapshot(it, string(results[0].PTest), tC.dirName+"-ptest")
				if tC.hasPX {
					gotest.MatchSnapshot(it, string(results[0].PXTest), tC.dirName+"-pxtest")
				}
			})
		}
	})
}

func (s *GeneratorTestSuite) TestE2ENoTestSuites(t *gotest.T) {
	t.When("packages without test suites", func(w *gotest.T) {
		for _, tC := range []struct {
			desc string
			args []string
		}{
			{"no test files", []string{"no_testfiles"}},
			{"non-existent path returns empty", []string{"testdata_e2e/nothing-here"}},
			{"stdlib package returns empty", []string{"strings"}},
			{"stdlib nested package returns empty", []string{"net/http"}},
		} {
			w.It("returns empty for "+tC.desc, func(it *gotest.T) {
				loaded, err := gotestgen.LoadPackages([]string{tC.args[0]}, nil)
				gotest.NoError(it, err)
				gotest.Empty(it, loaded)
			})
		}
	})
}

// --- helpers (shared with sharedfixture_e2e_suite_test.go) ---

func getExpectedOutputFile(t testing.TB, testdatadir, fileName string) string {
	t.Helper()
	f, err := os.Open(filepath.Join(testdatadir, fileName))
	if err != nil {
		t.Fatalf("open %s/%s: %v", testdatadir, fileName, err)
	}
	defer f.Close()

	buf, err := io.ReadAll(f)
	if err != nil {
		t.Fatalf("read %s/%s: %v", testdatadir, fileName, err)
	}
	els := bytes.SplitN(buf, []byte("\n"), 2)
	if len(els) != 2 {
		t.Fatalf("expected at least 2 lines in %s/%s", testdatadir, fileName)
	}
	firstLine := els[0]
	if !IS_GEN_FILE.Match(firstLine) {
		t.Fatalf("Must be a generated file! %s/%s", testdatadir, fileName)
	}
	return string(buf)
}
