package gotestgen

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"testing"

	"github.com/stretchr/testify/require"
)

var (
	IS_GEN_FILE = regexp.MustCompile(`^// Code generated by "go-test \(github\.com\/mvrahden\/go-test\)"; DO NOT EDIT\.(?:$|\n)`)
)

const (
	packageBase = "github.com/mvrahden/go-test"
)

func TestGeneratorGoldenExamples(t *testing.T) {
	for _, tC := range []struct {
		directory   string
		pkgName     string
		description string
	}{
		{"my", "github.com/mvrahden/go-test/examples/my", "standard test suites"},
		{"focus_suite", "github.com/mvrahden/go-test/examples/focus_suite", "focus test suites"},
	} {
		pkg := path.Join("..", "..", "examples", tC.directory)
		testdatadir := filepath.Join("..", "..", "examples", tC.directory)

		t.Run(fmt.Sprintf("Generate for package %q with %s", tC.directory, tC.description), func(t *testing.T) {
			pkgName, ptest, pxtest, err := Generate(pkg)
			require.NoError(t, err)
			require.Equal(t, tC.pkgName, pkgName)
			ptestExpected := getExpectedOutputFile(t, testdatadir, "gotest_gensuite_ptest.golden")
			require.Equal(t, ptestExpected, string(ptest))
			pxtestExpected := getExpectedOutputFile(t, testdatadir, "gotest_gensuite_pxtest.golden")
			require.Equal(t, pxtestExpected, string(pxtest))
		})
	}
}

func getExpectedOutputFile(t *testing.T, testdatadir, fileName string) string {
	f, err := os.Open(filepath.Join(testdatadir, fileName))
	require.NoError(t, err)
	defer f.Close()

	buf, err := io.ReadAll(f)
	require.NoError(t, err)
	els := bytes.SplitN(buf, []byte("\n"), 2)
	require.Len(t, els, 2)
	firstLine := els[0]
	require.True(t, IS_GEN_FILE.Match(firstLine), "Must be a generated file!")
	return string(buf)
}
