package gotestgen

import (
	"bytes"
	"fmt"
	"go/format"

	"github.com/mvrahden/go-test/internal/gotestast"
)

// SharedFixtureInfo describes a shared fixture to be run in a setup subprocess.
type SharedFixtureInfo struct {
	Identifier string            // type name e.g. "PostgresFixture"
	PkgPath    string            // import path e.g. "github.com/example/project/tests/fixtures"
	EnvTags    map[string]string // field name -> env var name
}

// DiscoverSharedFixtures scans CollectorResults for shared fixtures that are
// embedded in package fixtures. Returns deduplicated list.
func DiscoverSharedFixtures(results []CollectorResult) []SharedFixtureInfo {
	seen := map[string]bool{}
	var shared []SharedFixtureInfo
	for _, cr := range results {
		for _, f := range cr.Fixtures {
			if f.Kind != gotestast.SharedFixture {
				continue
			}
			key := f.PackagePath() + "." + f.Identifier()
			if seen[key] {
				continue
			}
			seen[key] = true
			shared = append(shared, SharedFixtureInfo{
				Identifier: f.Identifier(),
				PkgPath:    f.PackagePath(),
				EnvTags:    f.EnvTags,
			})
		}
	}
	return shared
}

// GenerateSharedSetup generates a standalone Go main package source that
// starts shared fixtures, writes env vars as JSON to stdout, then waits
// for SIGTERM/SIGINT before tearing down.
func GenerateSharedSetup(fixtures []SharedFixtureInfo) ([]byte, error) {
	if len(fixtures) == 0 {
		return nil, fmt.Errorf("no shared fixtures to generate setup for")
	}

	var buf bytes.Buffer

	// File header
	fmt.Fprintf(&buf, "// Code generated by \"go-test\"; DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package main\n\n")

	// Imports
	fmt.Fprintf(&buf, "import (\n")
	fmt.Fprintf(&buf, "\t\"encoding/json\"\n")
	fmt.Fprintf(&buf, "\t\"fmt\"\n")
	fmt.Fprintf(&buf, "\t\"os\"\n")
	fmt.Fprintf(&buf, "\t\"os/signal\"\n")
	fmt.Fprintf(&buf, "\t\"syscall\"\n\n")
	for i, sf := range fixtures {
		fmt.Fprintf(&buf, "\tsfpkg%d %q\n", i, sf.PkgPath)
	}
	fmt.Fprintf(&buf, ")\n\n")

	// Main function
	fmt.Fprintf(&buf, "func main() {\n")
	fmt.Fprintf(&buf, "\tenv := map[string]string{}\n\n")

	for i, sf := range fixtures {
		varName := fmt.Sprintf("sf%d", i)
		fmt.Fprintf(&buf, "\t%s := &sfpkg%d.%s{}\n", varName, i, sf.Identifier)
		fmt.Fprintf(&buf, "\tif err := %s.BeforeAll(); err != nil {\n", varName)
		// Teardown already-started fixtures in reverse
		for j := i - 1; j >= 0; j-- {
			fmt.Fprintf(&buf, "\t\tsf%d.AfterAll()\n", j)
		}
		fmt.Fprintf(&buf, "\t\tfmt.Fprintf(os.Stderr, \"%s.BeforeAll: %%v\\n\", err)\n", sf.Identifier)
		fmt.Fprintf(&buf, "\t\tos.Exit(1)\n")
		fmt.Fprintf(&buf, "\t}\n")
		for fieldName, envVar := range sf.EnvTags {
			fmt.Fprintf(&buf, "\tenv[%q] = %s.%s\n", envVar, varName, fieldName)
		}
		fmt.Fprintf(&buf, "\n")
	}

	fmt.Fprintf(&buf, "\tjson.NewEncoder(os.Stdout).Encode(env)\n\n")
	fmt.Fprintf(&buf, "\tsig := make(chan os.Signal, 1)\n")
	fmt.Fprintf(&buf, "\tsignal.Notify(sig, syscall.SIGTERM, syscall.SIGINT)\n")
	fmt.Fprintf(&buf, "\t<-sig\n\n")

	// Teardown in reverse order
	for i := len(fixtures) - 1; i >= 0; i-- {
		fmt.Fprintf(&buf, "\tsf%d.AfterAll()\n", i)
	}

	fmt.Fprintf(&buf, "}\n")

	return format.Source(buf.Bytes())
}
