package gotestgen

import (
	"bytes"
	"fmt"
	"go/format"

	"github.com/mvrahden/go-test/about"
)

// SharedFixtureInfo describes a shared fixture to be run in a setup subprocess.
type SharedFixtureInfo struct {
	Identifier     string // type name e.g. "PostgresFixture"
	PkgPath        string // import path e.g. "github.com/example/project/tests/fixtures"
	HasConfig      bool
	HasHydrate     bool
	HasDehydrate   bool
	TransferFields []string // exported fields that are serialized (all exported minus local)
	LocalFields    []string // exported fields assigned in Hydrate
}

// GenerateSharedSetup generates a standalone Go main package source that
// starts shared fixtures, serializes transferable fields as JSON to stdout,
// then waits for SIGTERM/SIGINT before tearing down.
func GenerateSharedSetup(fixtures []SharedFixtureInfo) ([]byte, error) {
	if len(fixtures) == 0 {
		return nil, fmt.Errorf("no shared fixtures to generate setup for")
	}

	type pkgImport struct {
		alias, path string
	}
	var imports []pkgImport
	pkgAlias := map[string]string{}
	for _, sf := range fixtures {
		if _, ok := pkgAlias[sf.PkgPath]; !ok {
			alias := fmt.Sprintf("sfpkg%d", len(imports))
			pkgAlias[sf.PkgPath] = alias
			imports = append(imports, pkgImport{alias, sf.PkgPath})
		}
	}

	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by %q; DO NOT EDIT.\n", about.ShortInfo())
	fmt.Fprintf(&buf, "package main\n\n")

	fmt.Fprintf(&buf, "import (\n")
	fmt.Fprintf(&buf, "\t\"context\"\n")
	fmt.Fprintf(&buf, "\t\"encoding/json\"\n")
	fmt.Fprintf(&buf, "\t\"fmt\"\n")
	fmt.Fprintf(&buf, "\t\"os\"\n")
	fmt.Fprintf(&buf, "\t\"os/signal\"\n")
	fmt.Fprintf(&buf, "\t\"syscall\"\n\n")
	for _, imp := range imports {
		fmt.Fprintf(&buf, "\t%s %q\n", imp.alias, imp.path)
	}
	fmt.Fprintf(&buf, ")\n\n")

	fmt.Fprintf(&buf, "func main() {\n")
	fmt.Fprintf(&buf, "\tctx := context.Background()\n")
	fmt.Fprintf(&buf, "\tstate := map[string]json.RawMessage{}\n\n")

	for i, sf := range fixtures {
		varName := fmt.Sprintf("sf%d", i)
		alias := pkgAlias[sf.PkgPath]
		fmt.Fprintf(&buf, "\t%s := &%s.%s{}\n", varName, alias, sf.Identifier)
		fmt.Fprintf(&buf, "\tif err := %s.BeforeAll(ctx); err != nil {\n", varName)
		for j := i - 1; j >= 0; j-- {
			fmt.Fprintf(&buf, "\t\tsf%d.AfterAll(ctx)\n", j)
		}
		fmt.Fprintf(&buf, "\t\tfmt.Fprintf(os.Stderr, \"%s.BeforeAll: %%v\\n\", err)\n", sf.Identifier)
		fmt.Fprintf(&buf, "\t\tos.Exit(1)\n")
		fmt.Fprintf(&buf, "\t}\n")

		// Serialize transferable fields as a struct
		stateKey := sf.PkgPath + "." + sf.Identifier
		if len(sf.TransferFields) > 0 {
			fmt.Fprintf(&buf, "\t{\n")
			fmt.Fprintf(&buf, "\t\ttype transfer struct {\n")
			for _, field := range sf.TransferFields {
				fmt.Fprintf(&buf, "\t\t\t%s interface{} `json:\"%s\"`\n", field, field)
			}
			fmt.Fprintf(&buf, "\t\t}\n")
			fmt.Fprintf(&buf, "\t\tb, err := json.Marshal(transfer{\n")
			for _, field := range sf.TransferFields {
				fmt.Fprintf(&buf, "\t\t\t%s: %s.%s,\n", field, varName, field)
			}
			fmt.Fprintf(&buf, "\t\t})\n")
			fmt.Fprintf(&buf, "\t\tif err != nil {\n")
			for j := i; j >= 0; j-- {
				fmt.Fprintf(&buf, "\t\t\tsf%d.AfterAll(ctx)\n", j)
			}
			fmt.Fprintf(&buf, "\t\t\tfmt.Fprintf(os.Stderr, \"%s: marshal: %%v\\n\", err)\n", sf.Identifier)
			fmt.Fprintf(&buf, "\t\t\tos.Exit(1)\n")
			fmt.Fprintf(&buf, "\t\t}\n")
			fmt.Fprintf(&buf, "\t\tstate[%q] = b\n", stateKey)
			fmt.Fprintf(&buf, "\t}\n")
		}
		fmt.Fprintf(&buf, "\n")
	}

	fmt.Fprintf(&buf, "\tjson.NewEncoder(os.Stdout).Encode(state)\n\n")
	fmt.Fprintf(&buf, "\tsig := make(chan os.Signal, 1)\n")
	fmt.Fprintf(&buf, "\tsignal.Notify(sig, syscall.SIGTERM, syscall.SIGINT)\n")
	fmt.Fprintf(&buf, "\t<-sig\n\n")

	for i := len(fixtures) - 1; i >= 0; i-- {
		fmt.Fprintf(&buf, "\tsf%d.AfterAll(ctx)\n", i)
	}

	fmt.Fprintf(&buf, "}\n")

	return format.Source(buf.Bytes())
}
