// Code generated by "go-test (github.com/mvrahden/go-test)"; DO NOT EDIT.

package my_test

import (
	"strings"
	"sync"
	"testing"

	"github.com/mvrahden/go-test/pkg/gotest"
	"github.com/stretchr/testify/require"
)

func TestMyTestSuite(t *testing.T) {
	s := MyTestSuite{}

	tt := gotest.NewT(t)
	type TestCaseRun struct {
		Name  string
		RunFn gotest.TestCase
	}
	newTestCaseRun := func(desc string, testFn gotest.TestCase) TestCaseRun {
		return TestCaseRun{desc, func(it *gotest.T) {
			s.BeforeEach(it)
			testFn(it)
			s.AfterEach(it)
		}}
	}
	allSequentialTestCases := []TestCaseRun{
		newTestCaseRun("TestSomethingAny", s.TestSomethingAny),
		newTestCaseRun("TestSomethingB", s.TestSomethingB),
		newTestCaseRun("TestSomethingDuration", s.TestSomethingDuration),
		newTestCaseRun("TestSomethingFunction", s.TestSomethingFunction),
		newTestCaseRun("TestSomethingSpecific", s.TestSomethingSpecific),
		newTestCaseRun("TestSomethingTime", s.TestSomethingTime),
		newTestCaseRun("FTestSomethingSpecific", s.FTestSomethingSpecific),
		newTestCaseRun("TestSomethingAsync", func(t *gotest.T) {
			wg := &sync.WaitGroup{}
			wg.Add(1)
			doneFn := func() {
				wg.Done()
			}
			s.TestSomethingAsync(t, doneFn)
			wg.Wait()
		}),
	}

	s.BeforeAll(tt)
	for _, tc := range allSequentialTestCases {
		t.Run(tc.Name, func(t *testing.T) {
			tc.RunFn(tt)
		})
	}
	s.AfterAll(tt)

	var actualSequence string
	for v := range s.ExecutedC {
		actualSequence += v + ":"
	}
	require.GreaterOrEqual(t, len(actualSequence), 100)
	require.True(t, strings.HasPrefix(actualSequence, "BeforeAll:"))
	require.True(t, strings.HasSuffix(actualSequence, ":AfterAll:"))
	require.Contains(t, actualSequence, "BeforeEach:TestSomethingAny:AfterEach")
	require.Contains(t, actualSequence, "BeforeEach:TestSomethingB:AfterEach")
	require.Contains(t, actualSequence, "BeforeEach:TestSomethingDuration:AfterEach")
	require.Contains(t, actualSequence, "BeforeEach:TestSomethingFunction:AfterEach")
	require.Contains(t, actualSequence, "BeforeEach:TestSomethingSpecific:AfterEach")
	require.Contains(t, actualSequence, "BeforeEach:TestSomethingTime:AfterEach")
	require.Contains(t, actualSequence, "BeforeEach:FTestSomethingSpecific:AfterEach")
	require.NotContains(t, actualSequence, "XTestSomethingSpecific")
}

func TestMyParallelTestSuite(t *testing.T) {
	s := MyTestSuite{}

	tt := gotest.NewT(t)
	allSequentialTestCases := []gotest.TestCase{
		s.TestParallelSomethingC,
		s.TestParallelSomethingD,
		s.TestParallelSomethingE,
	}
	s.BeforeAll(tt)
	for _, tc := range allSequentialTestCases {
		s.BeforeEach(tt)
		tc(tt)
		s.AfterEach(tt)
	}
	s.AfterAll(tt)

	var actualSequence string
	for v := range s.ExecutedC {
		actualSequence += v + ":"
	}
	require.GreaterOrEqual(t, len(actualSequence), 100)
	require.Contains(t, actualSequence, "TestParallelSomethingC")
	require.Contains(t, actualSequence, "TestParallelSomethingD")
	require.Contains(t, actualSequence, "TestParallelSomethingE")
}
