// Code generated by "go-test (github.com/mvrahden/go-test)"; DO NOT EDIT.

package my_test

import (
	"github.com/mvrahden/go-test/examples/my"
	"github.com/mvrahden/go-test/pkg/gotest"
	"sync"
	"testing"
)

type ƒƒ_GOTEST_my_MyNoopTestSuite struct {
	my.MyNoopTestSuite
}

func (ts *ƒƒ_GOTEST_my_MyNoopTestSuite) BeforeAll(it *gotest.T)  {}
func (ts *ƒƒ_GOTEST_my_MyNoopTestSuite) AfterAll(it *gotest.T)   {}
func (ts *ƒƒ_GOTEST_my_MyNoopTestSuite) BeforeEach(it *gotest.T) {}
func (ts *ƒƒ_GOTEST_my_MyNoopTestSuite) AfterEach(it *gotest.T)  {}

func Test_my_MyNoopTestSuite(t *testing.T) {
	s := &ƒƒ_GOTEST_my_MyNoopTestSuite{}

	testCases := []gotest.TestCase{}

	tt := gotest.NewT(t)
	t.Cleanup(func() {
		s.AfterAll(tt)
	})
	s.BeforeAll(tt)
	for _, tc := range testCases {
		tc(tt)
	}
}

type ƒƒ_GOTEST_my_MyNoopParallelTestSuite struct {
	my.MyNoopParallelTestSuite
}

func (ts *ƒƒ_GOTEST_my_MyNoopParallelTestSuite) BeforeAll(it *gotest.T)  {}
func (ts *ƒƒ_GOTEST_my_MyNoopParallelTestSuite) AfterAll(it *gotest.T)   {}
func (ts *ƒƒ_GOTEST_my_MyNoopParallelTestSuite) BeforeEach(it *gotest.T) {}
func (ts *ƒƒ_GOTEST_my_MyNoopParallelTestSuite) AfterEach(it *gotest.T)  {}

func Test_my_MyNoopParallelTestSuite(t *testing.T) {
	s := &ƒƒ_GOTEST_my_MyNoopParallelTestSuite{}
	t.Parallel()

	testCases := []gotest.TestCase{}

	tt := gotest.NewT(t)
	t.Cleanup(func() {
		s.AfterAll(tt)
	})
	s.BeforeAll(tt)
	for _, tc := range testCases {
		tc(tt)
	}
}

type ƒƒ_GOTEST_my_MyTestSuite struct {
	my.MyTestSuite
}

func (ts *ƒƒ_GOTEST_my_MyTestSuite) BeforeAll(it *gotest.T)  { ts.MyTestSuite.BeforeAll(it) }
func (ts *ƒƒ_GOTEST_my_MyTestSuite) AfterAll(it *gotest.T)   { ts.MyTestSuite.AfterAll(it) }
func (ts *ƒƒ_GOTEST_my_MyTestSuite) BeforeEach(it *gotest.T) { ts.MyTestSuite.BeforeEach(it) }
func (ts *ƒƒ_GOTEST_my_MyTestSuite) AfterEach(it *gotest.T)  { ts.MyTestSuite.AfterEach(it) }

func Test_my_MyTestSuite(t *testing.T) {
	s := &ƒƒ_GOTEST_my_MyTestSuite{}

	newTestCase := func(desc string, testFn gotest.TestCase) gotest.TestCase {
		return func(tt *gotest.T) {
			t := tt.T()
			t.Run(desc, func(it *testing.T) {
				ttt := gotest.NewT(it)
				s.BeforeEach(ttt)
				testFn(ttt)
				s.AfterEach(ttt)
			})
		}
	}
	newParallelTestCase := func(desc string, wg *sync.WaitGroup, testFn gotest.TestCase) gotest.TestCase {
		wg.Add(1)
		return func(tt *gotest.T) {
			t := tt.T()
			t.Run(desc, func(it *testing.T) {
				it.Parallel()
				ttt := gotest.NewT(it)
				s.BeforeEach(ttt)
				testFn(ttt)
				s.AfterEach(ttt)
				wg.Done()
			})
		}
	}
	wg := &sync.WaitGroup{}

	testCases := []gotest.TestCase{
		newTestCase("F_TestSomethingSpecific", s.F_TestSomethingSpecific),
		newParallelTestCase("F_TestParallelSomethingC", wg, s.F_TestParallelSomethingC),
	}

	tt := gotest.NewT(t)
	t.Cleanup(func() {
		wg.Wait()
		s.AfterAll(tt)
	})
	s.BeforeAll(tt)
	for _, tc := range testCases {
		tc(tt)
	}
}

type ƒƒ_GOTEST_MyNoopTestSuite struct {
	MyNoopTestSuite
}

func (ts *ƒƒ_GOTEST_MyNoopTestSuite) BeforeAll(it *gotest.T)  {}
func (ts *ƒƒ_GOTEST_MyNoopTestSuite) AfterAll(it *gotest.T)   {}
func (ts *ƒƒ_GOTEST_MyNoopTestSuite) BeforeEach(it *gotest.T) {}
func (ts *ƒƒ_GOTEST_MyNoopTestSuite) AfterEach(it *gotest.T)  {}

func TestMyNoopTestSuite(t *testing.T) {
	s := &ƒƒ_GOTEST_MyNoopTestSuite{}

	testCases := []gotest.TestCase{}

	tt := gotest.NewT(t)
	t.Cleanup(func() {
		s.AfterAll(tt)
	})
	s.BeforeAll(tt)
	for _, tc := range testCases {
		tc(tt)
	}
}

type ƒƒ_GOTEST_MyTestSuite struct {
	MyTestSuite
}

func (ts *ƒƒ_GOTEST_MyTestSuite) BeforeAll(it *gotest.T)  { ts.MyTestSuite.BeforeAll(it) }
func (ts *ƒƒ_GOTEST_MyTestSuite) AfterAll(it *gotest.T)   { ts.MyTestSuite.AfterAll(it) }
func (ts *ƒƒ_GOTEST_MyTestSuite) BeforeEach(it *gotest.T) { ts.MyTestSuite.BeforeEach(it) }
func (ts *ƒƒ_GOTEST_MyTestSuite) AfterEach(it *gotest.T)  { ts.MyTestSuite.AfterEach(it) }

func TestMyTestSuite(t *testing.T) {
	s := &ƒƒ_GOTEST_MyTestSuite{}

	newTestCase := func(desc string, testFn gotest.TestCase) gotest.TestCase {
		return func(tt *gotest.T) {
			t := tt.T()
			t.Run(desc, func(it *testing.T) {
				ttt := gotest.NewT(it)
				s.BeforeEach(ttt)
				testFn(ttt)
				s.AfterEach(ttt)
			})
		}
	}

	testCases := []gotest.TestCase{
		newTestCase("F_TestSomethingSpecific", s.F_TestSomethingSpecific),
	}

	tt := gotest.NewT(t)
	t.Cleanup(func() {
		s.AfterAll(tt)
	})
	s.BeforeAll(tt)
	for _, tc := range testCases {
		tc(tt)
	}
}

func Test_my_X_MySkippedTestSuite(t *testing.T) {
	t.Skipf("test suite was excluded by user")
}

func TestX_MySkippedTestSuite(t *testing.T) {
	t.Skipf("test suite was excluded by user")
}
