// Code generated by "gotest (github.com/mvrahden/go-test)"; DO NOT EDIT.

package gotestrunner_test

import (
	"github.com/mvrahden/go-test/pkg/gotest"
	"sync"
	"testing"
)

//go:noinline
func ƒƒ_GOTEST_exec(fn gotest.TestCase, t *gotest.T) { fn(t) }

type ƒƒ_GOTEST_GotestrunnerProcessTestSuite struct {
	GotestrunnerProcessTestSuite
}

func (ts *ƒƒ_GOTEST_GotestrunnerProcessTestSuite) BeforeAll(it *gotest.T)  {}
func (ts *ƒƒ_GOTEST_GotestrunnerProcessTestSuite) AfterAll(it *gotest.T)   {}
func (ts *ƒƒ_GOTEST_GotestrunnerProcessTestSuite) BeforeEach(it *gotest.T) {}
func (ts *ƒƒ_GOTEST_GotestrunnerProcessTestSuite) AfterEach(it *gotest.T)  {}

func TestGotestrunnerProcessTestSuite(t *testing.T) {
	s := &ƒƒ_GOTEST_GotestrunnerProcessTestSuite{}
	ƒcfg := gotest.DefaultSuiteConfig()
	gotest.OverlaySuiteConfig(&ƒcfg, s.GotestrunnerProcessTestSuite.SuiteConfig())
	wg := &sync.WaitGroup{}

	ƒsetupT := gotest.NewT(t)
	if ƒcfg.SetupTimeout > 0 {
		ƒsetupT = gotest.NewTWithDeadline(t, ƒcfg.SetupTimeout)
	}
	t.Cleanup(func() {
		wg.Wait()
		ƒteardownT := gotest.NewT(t)
		if ƒcfg.SetupTimeout > 0 {
			ƒteardownT = gotest.NewTWithDeadline(t, ƒcfg.SetupTimeout)
		}
		s.AfterAll(ƒteardownT)
	})
	s.BeforeAll(ƒsetupT)

	t.Run("TestGracefulTermination", func(it *testing.T) {
		wg.Add(1)
		it.Parallel()
		defer wg.Done()
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestGracefulTermination, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestTeardownBudget", func(it *testing.T) {
		wg.Add(1)
		it.Parallel()
		defer wg.Done()
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestTeardownBudget, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestProcessGroupSetup", func(it *testing.T) {
		wg.Add(1)
		it.Parallel()
		defer wg.Done()
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestProcessGroupSetup, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestProcessGroupCancel", func(it *testing.T) {
		wg.Add(1)
		it.Parallel()
		defer wg.Done()
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestProcessGroupCancel, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestProcessGroupTermination", func(it *testing.T) {
		wg.Add(1)
		it.Parallel()
		defer wg.Done()
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestProcessGroupTermination, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

}

type ƒƒ_GOTEST_GotestrunnerTestSuite struct {
	GotestrunnerTestSuite
}

func (ts *ƒƒ_GOTEST_GotestrunnerTestSuite) BeforeAll(it *gotest.T)  {}
func (ts *ƒƒ_GOTEST_GotestrunnerTestSuite) AfterAll(it *gotest.T)   {}
func (ts *ƒƒ_GOTEST_GotestrunnerTestSuite) BeforeEach(it *gotest.T) {}
func (ts *ƒƒ_GOTEST_GotestrunnerTestSuite) AfterEach(it *gotest.T)  {}

func TestGotestrunnerTestSuite(t *testing.T) {
	s := &ƒƒ_GOTEST_GotestrunnerTestSuite{}
	ƒcfg := gotest.DefaultSuiteConfig()

	ƒsetupT := gotest.NewT(t)
	if ƒcfg.SetupTimeout > 0 {
		ƒsetupT = gotest.NewTWithDeadline(t, ƒcfg.SetupTimeout)
	}
	t.Cleanup(func() {
		ƒteardownT := gotest.NewT(t)
		if ƒcfg.SetupTimeout > 0 {
			ƒteardownT = gotest.NewTWithDeadline(t, ƒcfg.SetupTimeout)
		}
		s.AfterAll(ƒteardownT)
	})
	s.BeforeAll(ƒsetupT)

	t.Run("TestIsGoTestFlag", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestIsGoTestFlag, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestCoverProfile", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestCoverProfile, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestOverlayManagement", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestOverlayManagement, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestBuildSuiteCmd", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestBuildSuiteCmd, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestOutputCollector", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestOutputCollector, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestOutputFormatting", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestOutputFormatting, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestSplitTopLevelOr", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestSplitTopLevelOr, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestHasVerboseFlag", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestHasVerboseFlag, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestSuiteRunFilter", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestSuiteRunFilter, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestComputeConcurrency", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestComputeConcurrency, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestExtractParallelValue", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestExtractParallelValue, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestInjectParallel", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestInjectParallel, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestOutputGolden", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestOutputGolden, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestParseExecFlags", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestParseExecFlags, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestAssignCoverProfiles", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestAssignCoverProfiles, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestBuildExtraEnv", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestBuildExtraEnv, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

	t.Run("TestSharedFixtureProcess", func(it *testing.T) {
		ttt := gotest.NewT(it)
		if ƒcfg.Timeout > 0 {
			ttt = gotest.NewTWithDeadline(it, ƒcfg.Timeout)
		}
		defer s.AfterEach(ttt)
		s.BeforeEach(ttt)
		ƒƒ_GOTEST_exec(s.TestSharedFixtureProcess, ttt)
	})
	if ƒcfg.FailFast && t.Failed() {
		return
	}

}
