{{- /* Declaration of file header */ -}}
{{ with $h := .Header -}}
// Code generated by "{{ .RepoName }}"; DO NOT EDIT.

package {{ .PackageName }}

{{/* Declaration of file imports */}}
{{- if .Imports -}}
import (
{{- range $i := .Imports }}
  {{ if $i.Name }}{{ $i.Name }} {{ end }}{{ printf "%q" $i.Path }}
{{- end }}
)
{{- end }}
{{ end -}}
