// Code generated by "{{ .RepoInfo }}"; DO NOT EDIT.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/signal"
	"syscall"
{{ range .Imports }}
	{{ .Alias }} {{ printf "%q" .Path }}
{{- end }}
)

func main() {
	ctx := context.Background()
	state := map[string]json.RawMessage{}
{{ range $f := .Fixtures }}
	{{ $f.VarName }} := &{{ $f.QualifiedType }}{}
	if err := {{ $f.VarName }}.BeforeAll(ctx); err != nil {
{{- range $f.BeforeAllRollbackVars }}
		{{ . }}.AfterAll(ctx)
{{- end }}
		fmt.Fprintf(os.Stderr, "{{ $f.Identifier }}.BeforeAll: %v\n", err)
		os.Exit(1)
	}
{{- if $f.TransferFields }}
	{
		type transfer struct {
{{- range $f.TransferFields }}
			{{ . }} interface{} `json:"{{ . }}"`
{{- end }}
		}
		b, err := json.Marshal(transfer{
{{- range $f.TransferFields }}
			{{ . }}: {{ $f.VarName }}.{{ . }},
{{- end }}
		})
		if err != nil {
{{- range $f.MarshalRollbackVars }}
			{{ . }}.AfterAll(ctx)
{{- end }}
			fmt.Fprintf(os.Stderr, "{{ $f.Identifier }}: marshal: %v\n", err)
			os.Exit(1)
		}
		state[{{ printf "%q" $f.StateKey }}] = b
	}
{{- end }}
{{ end }}
	json.NewEncoder(os.Stdout).Encode(state)

	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGTERM, syscall.SIGINT)
	<-sig
{{ range .TeardownVars }}
	{{ . }}.AfterAll(ctx)
{{- end }}
}
