// Code generated by "{{ .RepoInfo }}"; DO NOT EDIT.
package main

import (
	"bufio"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/signal"
	"strings"
	"sync"
	"syscall"
	"time"

	gotest {{ printf "%q" .GotestImportPath }}
	gotestruntime {{ printf "%q" .GotestRuntimeImportPath }}
{{ range .Imports }}
	{{ .Alias }} {{ printf "%q" .Path }}
{{- end }}
)

func ƒquote(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

// ƒcommand is one runner instruction on stdin: start or tear down a set of
// fixtures by state key, mid-run, at a window boundary.
type ƒcommand struct {
	Verb string   `json:"verb"`
	Keys []string `json:"keys"`
}

func ƒhasKey(keys []string, key string) bool {
	for _, k := range keys {
		if k == key {
			return true
		}
	}
	return false
}

{{- /*
  Configs start as the defaults and are derived inside each fixture's setup,
  not here: a config marker that panics at the top of main would kill the
  process before the handshake, attributed to nothing. A fixture whose
  derivation fails reports the error, its dependents and its teardown skip it,
  and the defaults it keeps are never read again.
*/}}
func main() {
{{- /*
  Shutdown-capable from birth: SIGTERM at any phase cancels ƒctx, so setup
  attempts abort instead of the default disposition killing the process
  mid-lifecycle, and the epilogue below still releases whatever came up.
*/}}
	ƒctx, ƒstop := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT)
	defer ƒstop()
{{ range $f := .Fixtures }}
	{{ $f.VarName }} := &{{ $f.QualifiedType }}{}
	ƒcfg_{{ $f.VarName }} := gotest.DefaultFixtureConfig()
{{ end }}
	ƒerrs := make([]error, {{ len .Fixtures }})
	ƒstarted := make([]bool, {{ len .Fixtures }})
	ƒtorn := make([]bool, {{ len .Fixtures }})
{{ range $f := .Fixtures }}
	ƒdone_{{ $f.VarName }} := make(chan struct{})
{{- end }}

{{- /*
  One setup body per fixture, shared verbatim by the up-front phase and the
  StartKeys verb: same config derivation, same dependency gating, same retry
  and budget policy through RunFixtureSetup. A fixture starts at most once —
  its window opens exactly one time per run.
*/}}
{{ range $i, $f := .Fixtures }}
	ƒsetup_{{ $f.VarName }} := func() {
		if ƒstarted[{{ $i }}] {
			return
		}
		ƒstarted[{{ $i }}] = true
		defer close(ƒdone_{{ $f.VarName }})
{{- if $f.HasConfig }}
{{- /*
  Derived before the dependency wait, on the bare instance — the same moment
  the in-process harness derives it, before any parent fields are assigned.
*/}}
		ƒcfg, ƒerr := gotestruntime.DeriveFixtureConfig("{{ $f.Identifier }}", {{ $f.VarName }}.SharedFixtureConfig)
		if ƒerr != nil {
			ƒerrs[{{ $i }}] = ƒerr
			return
		}
		ƒcfg_{{ $f.VarName }} = ƒcfg
{{- end }}
{{- range $dep := $f.DependsOnVars }}
		<-ƒdone_{{ $dep }}
{{- end }}
{{- range $idx := $f.DependsOnIndices }}
		if ƒerrs[{{ $idx }}] != nil {
			ƒerrs[{{ $i }}] = fmt.Errorf("skipped: dependency failed")
			return
		}
{{- end }}
{{- range $pa := $f.ParentAssignments }}
		{{ $f.VarName }}.{{ $pa.FieldName }} = {{ $pa.ParentVar }}
{{- end }}
{{- /*
  One policy, shared with the in-process DAG: a panic here would otherwise kill
  the process holding every sibling fixture's resources, so none of their
  AfterAlls would ever run. RunFixtureSetup also writes the per-attempt and
  final FAIL: lines to stderr.
*/}}
		ƒerrs[{{ $i }}] = gotestruntime.RunFixtureSetup(ƒctx, gotestruntime.FixtureSetup{
			Name:       "{{ $f.Identifier }}",
			Timeout:    ƒcfg_{{ $f.VarName }}.Timeout,
			Budget:     {{ if $f.HasConfig }}ƒcfg_{{ $f.VarName }}.Timeout{{ else }}0{{ end }},
			Retries:    ƒcfg_{{ $f.VarName }}.Retries,
			RetryDelay: ƒcfg_{{ $f.VarName }}.RetryDelay,
			BeforeAll:  {{ $f.VarName }}.BeforeAll,
		})
		if ƒerrs[{{ $i }}] != nil {
			return
		}
{{- if $f.TransferFields }}
		{
			type transfer struct {
{{- range $f.TransferFields }}
				{{ . }} interface{} `json:"{{ . }}"`
{{- end }}
			}
			b, err := json.Marshal(transfer{
{{- range $f.TransferFields }}
				{{ . }}: {{ $f.VarName }}.{{ . }},
{{- end }}
			})
			if err != nil {
				ƒerrs[{{ $i }}] = fmt.Errorf("marshal: %w", err)
				fmt.Fprintf(os.Stderr, "{{ $f.Identifier }}: marshal: %v\n", err)
				return
			}
			fmt.Fprintf(os.Stdout, "{\"key\":%s,\"state\":%s}\n", ƒquote("{{ $f.StateKey }}"), string(b))
		}
{{- else }}
		fmt.Fprintf(os.Stdout, "{\"key\":%s,\"state\":{}}\n", ƒquote("{{ $f.StateKey }}"))
{{- end }}
	}
{{ end }}

{{- /*
  One teardown body per fixture, shared by the TeardownKeys verb and the
  epilogue: whichever fires first wins, the other finds ƒtorn set and skips —
  the terminal teardown owns exactly the remainder. A fixture that never
  started, or whose setup failed, has nothing to release; one whose setup
  merely overran its budget still initialized, so it is torn down like a
  success. Panics are contained and a declared Timeout is a verdict — the
  same policy the in-process DAG runs under.
*/}}
{{ range $f := .Fixtures }}
	ƒteardown_{{ $f.VarName }} := func() bool {
		if ƒtorn[{{ $f.Index }}] || !ƒstarted[{{ $f.Index }}] {
			ƒtorn[{{ $f.Index }}] = true
			return false
		}
		ƒtorn[{{ $f.Index }}] = true
		if ƒerrs[{{ $f.Index }}] == nil || errors.Is(ƒerrs[{{ $f.Index }}], gotestruntime.ErrSetupOverran) {
			return gotestruntime.RunFixtureTeardown(context.Background(), gotestruntime.FixtureTeardown{
				Name:     "{{ $f.Identifier }}",
				Timeout:  ƒcfg_{{ $f.VarName }}.Timeout,
				Budget:   {{ if $f.HasConfig }}ƒcfg_{{ $f.VarName }}.Timeout{{ else }}0{{ end }},
				AfterAll: {{ $f.VarName }}.AfterAll,
			})
		}
		return false
	}
{{ end }}

{{- /*
  Up-front phase: every non-deferred fixture, concurrently, gated by the
  dependency channels. Deferred fixtures wait for their StartKeys window —
  their dependencies are non-deferred or ordered earlier in the same command,
  so their channel waits can never deadlock.
*/}}
	var ƒwg sync.WaitGroup
{{ range $f := .Fixtures }}
{{- if not $f.Deferred }}
	ƒwg.Add(1)
	go func() {
		defer ƒwg.Done()
		ƒsetup_{{ $f.VarName }}()
	}()
{{- end }}
{{ end }}
	ƒwg.Wait()

	ƒanyFailed := false
	for _, e := range ƒerrs {
		if e != nil {
			ƒanyFailed = true
			break
		}
	}

{{- /*
  Teardown is strictly sequential, so the budget the supervisor gets is the
  SUM of the members' budgets: a max would force-kill a set of teardowns that
  each obeyed its own declared Timeout. Deferred fixtures are counted at their
  default config — their derivation runs at StartKeys time. Reported on both
  _done forms — a failed setup still has succeeded siblings to release under
  this budget.
*/}}
	var ƒbudget time.Duration
{{ range $f := .Fixtures }}
	ƒbudget += gotestruntime.SupervisorBudget(ƒcfg_{{ $f.VarName }}.Timeout)
{{ end }}
	ƒbudgetStr := ƒquote((ƒbudget + 30*time.Second).String())

	if ƒanyFailed {
		fmt.Fprintf(os.Stdout, "{\"key\":\"_done\",\"error\":\"one or more shared fixtures failed\",\"teardownBudget\":%s}\n", ƒbudgetStr)
	} else {
		fmt.Fprintf(os.Stdout, "{\"key\":\"_done\",\"teardownBudget\":%s}\n", ƒbudgetStr)
	}

	ƒteardownFailed := false

{{- /*
  Window commands until shutdown. The runner owns shutdown TIMING — only it
  knows when every suite has stopped using the fixtures — so even a failed
  setup reports and then serves commands until the signal instead of tearing
  down on its own; this process owns shutdown EXECUTION. StartKeys runs in
  DAG order and TeardownKeys in reverse-DAG order because the fixture lists
  below are generated in topological order. Each command is acknowledged on
  stdout with a _cmd line carrying the joined per-fixture failures. A SIGTERM
  that already arrived (canceling setup above) has ƒctx closed and falls
  straight through.
*/}}
	ƒcmds := make(chan ƒcommand)
	go func() {
		ƒsc := bufio.NewScanner(os.Stdin)
		for ƒsc.Scan() {
			var ƒc ƒcommand
			if json.Unmarshal(ƒsc.Bytes(), &ƒc) != nil {
				continue
			}
			select {
			case ƒcmds <- ƒc:
			case <-ƒctx.Done():
				return
			}
		}
	}()

ƒloop:
	for {
		select {
		case <-ƒctx.Done():
			break ƒloop
		case ƒc := <-ƒcmds:
			var ƒcmdErrs []string
			switch ƒc.Verb {
			case "start":
{{- range $f := .Fixtures }}
				if ƒhasKey(ƒc.Keys, "{{ $f.StateKey }}") {
					ƒsetup_{{ $f.VarName }}()
					if ƒerrs[{{ $f.Index }}] != nil {
						ƒcmdErrs = append(ƒcmdErrs, "{{ $f.Identifier }}: "+ƒerrs[{{ $f.Index }}].Error())
					}
				}
{{- end }}
			case "teardown":
{{- range .TeardownFixtures }}
				if ƒhasKey(ƒc.Keys, "{{ .StateKey }}") {
					if ƒteardown_{{ .VarName }}() {
						ƒteardownFailed = true
						ƒcmdErrs = append(ƒcmdErrs, "{{ .Identifier }}: teardown failed")
					}
				}
{{- end }}
			default:
				ƒcmdErrs = append(ƒcmdErrs, "unknown verb: "+ƒc.Verb)
			}
			fmt.Fprintf(os.Stdout, "{\"key\":\"_cmd\",\"error\":%s}\n", ƒquote(strings.Join(ƒcmdErrs, "; ")))
		}
	}

{{- /*
  Terminal teardown: everything still resident, in reverse-DAG order. Keys an
  earlier TeardownKeys already released are skipped via ƒtorn — one owner per
  fixture teardown, always.
*/}}
{{ range .TeardownFixtures }}
	if ƒteardown_{{ .VarName }}() {
		ƒteardownFailed = true
	}
{{- end }}

{{- /*
  Exit 1 for a lifecycle failure of either kind. The runner reads a teardown
  failure from this exact status (gotestrunner.sharedTeardownFailedExit) when
  setup succeeded; a setup failure was already reported on the _done line, and
  a StartKeys failure on its _cmd line — deferred errors are the runner's to
  book, not this status's. A clean exit is the runner's only proof that
  teardown ran and passed.
*/}}
	if ƒanyFailed || ƒteardownFailed {
		os.Exit(1)
	}
}
