// Code generated by "{{ .RepoInfo }}"; DO NOT EDIT.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"

	gotest {{ printf "%q" .GotestImportPath }}
{{ range .Imports }}
	{{ .Alias }} {{ printf "%q" .Path }}
{{- end }}
)

func main() {
	state := map[string]json.RawMessage{}
{{ range $f := .Fixtures }}
	{{ $f.VarName }} := &{{ $f.QualifiedType }}{}
	ƒcfg_{{ $f.VarName }} := gotest.DefaultFixtureConfig()
{{- if $f.HasConfig }}
	gotest.OverlayFixtureConfig(&ƒcfg_{{ $f.VarName }}, {{ $f.VarName }}.SharedFixtureConfig())
{{- end }}
{{ end }}
	ƒerrs := make([]error, {{ len .Fixtures }})
	var ƒwg sync.WaitGroup
{{ range $i, $f := .Fixtures }}
	ƒwg.Add(1)
	go func() {
		defer ƒwg.Done()
		ƒattempts := 1 + ƒcfg_{{ $f.VarName }}.Retries
		for ƒj := range ƒattempts {
			ctx := context.Background()
			if ƒcfg_{{ $f.VarName }}.Timeout > 0 {
				var cancel context.CancelFunc
				ctx, cancel = context.WithTimeout(ctx, ƒcfg_{{ $f.VarName }}.Timeout)
				defer cancel()
			}
			ƒerrs[{{ $i }}] = {{ $f.VarName }}.BeforeAll(ctx)
			if ƒerrs[{{ $i }}] == nil {
				break
			}
			if ƒj < ƒattempts-1 {
				fmt.Fprintf(os.Stderr, "{{ $f.Identifier }}.BeforeAll attempt %d/%d failed: %v\n", ƒj+1, ƒattempts, ƒerrs[{{ $i }}])
				if ƒcfg_{{ $f.VarName }}.RetryDelay > 0 {
					time.Sleep(ƒcfg_{{ $f.VarName }}.RetryDelay)
				}
			}
		}
		if ƒerrs[{{ $i }}] != nil {
			fmt.Fprintf(os.Stderr, "{{ $f.Identifier }}.BeforeAll failed after %d attempt(s): %v\n", 1+ƒcfg_{{ $f.VarName }}.Retries, ƒerrs[{{ $i }}])
		}
	}()
{{ end }}
	ƒwg.Wait()

	ƒanyFailed := false
	for _, e := range ƒerrs {
		if e != nil {
			ƒanyFailed = true
			break
		}
	}
	if ƒanyFailed {
{{ range $i, $f := .Fixtures }}
		if ƒerrs[{{ $i }}] == nil {
			{{ $f.VarName }}.AfterAll(context.Background())
		}
{{ end }}
		os.Exit(1)
	}
{{ range $f := .Fixtures }}
{{- if $f.TransferFields }}
	{
		type transfer struct {
{{- range $f.TransferFields }}
			{{ . }} interface{} `json:"{{ . }}"`
{{- end }}
		}
		b, err := json.Marshal(transfer{
{{- range $f.TransferFields }}
			{{ . }}: {{ $f.VarName }}.{{ . }},
{{- end }}
		})
		if err != nil {
{{ range $.TeardownVars }}
			{{ . }}.AfterAll(context.Background())
{{- end }}
			fmt.Fprintf(os.Stderr, "{{ $f.Identifier }}: marshal: %v\n", err)
			os.Exit(1)
		}
		state[{{ printf "%q" $f.StateKey }}] = b
	}
{{- end }}
{{ end }}
	json.NewEncoder(os.Stdout).Encode(state)

	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGTERM, syscall.SIGINT)
	<-sig
{{ range .TeardownVars }}
	{
		ctx := context.Background()
		if ƒcfg_{{ . }}.Timeout > 0 {
			var cancel context.CancelFunc
			ctx, cancel = context.WithTimeout(ctx, ƒcfg_{{ . }}.Timeout)
			defer cancel()
		}
		{{ . }}.AfterAll(ctx)
	}
{{- end }}
}
