package gotestast

import (
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"regexp"
	"strings"

	"github.com/dlclark/regexp2"

	"github.com/mvrahden/go-test/about"
	"github.com/mvrahden/go-test/internal/x/slices"
	"golang.org/x/tools/go/packages"
)

type regexpW struct {
	*regexp2.Regexp
}

func (r *regexpW) MatchString(s string) bool {
	res, _ := r.Regexp.MatchString(s)
	return res
}

var (
	GEN_TESTSUITE_FILE   = regexp.MustCompile(`^// Code generated by "gotest \(github\.com/mvrahden/go-test\)"; DO NOT EDIT\.(?:$|\n)`)
	IS_TEST_SUITE        = &regexpW{regexp2.MustCompile(`^(?!ƒƒ_GOTEST_|_)(?:X_|F_)?.+TestSuite$`, regexp2.ECMAScript)}
	IS_TEST_SUITE_METHOD = &regexpW{regexp2.MustCompile(`^(?:BeforeAll|AfterAll|BeforeEach|AfterEach|SuiteConfig|SuiteGuard|(?:X_|F_)?Test.+)$`, regexp2.ECMAScript)}
	IS_BEFORE_ALL        = regexp.MustCompile(`^BeforeAll$`)
	IS_AFTER_ALL         = regexp.MustCompile(`^AfterAll$`)
	IS_BEFORE_EACH       = regexp.MustCompile(`^BeforeEach$`)
	IS_AFTER_EACH        = regexp.MustCompile(`^AfterEach$`)
	IS_TEST_CASE       = &regexpW{regexp2.MustCompile(`^(?:X_|F_)?Test.+$`, regexp2.ECMAScript)} // matches all test cases
	IS_TEST_CASE_ASYNC = regexp.MustCompile(`^(?:X_|F_)?Test.+Async$`)                          // matches all test cases with async suffix
)

type TestSuiteSpecSet []*TestSuiteSpec
type SkippedTestSuites []*TestSuiteSpec
type SkippedTestCases map[*TestSuiteSpec][]*TestSuiteMethod

func (ts TestSuiteSpecSet) ReduceToEffectiveSet() (TestSuiteSpecSet, SkippedTestSuites, SkippedTestCases) {
	effectiveSet := append((TestSuiteSpecSet)(nil), ts...)

	var skippedTestSuites SkippedTestSuites
	skippedTestCases := SkippedTestCases{}
	{ // split focused from unfocused
		focused, unfocused := slices.SplitBy(effectiveSet, func(v *TestSuiteSpec, _ int) bool {
			return v.IsFocused()
		})
		effectiveSet = unfocused
		if len(focused) > 0 {
			effectiveSet, skippedTestSuites = focused, append(skippedTestSuites, unfocused...)
		}
	}

	{ // split excluded from included
		excluded, included := slices.SplitBy(effectiveSet, func(v *TestSuiteSpec, _ int) bool {
			return v.IsExcluded()
		})
		effectiveSet = included
		if len(excluded) > 0 {
			skippedTestSuites = append(skippedTestSuites, excluded...)
		}
	}

	slices.Range(effectiveSet, func(v *TestSuiteSpec, _ int) {
		skippedTestCases[v] = nil
	})

	{ // reduce SEQUENTIAL test cases
		slices.Range(effectiveSet, func(v *TestSuiteSpec, _ int) {
			// split focused from unfocused
			focused, unfocused := slices.SplitBy(v.th.TestCases, func(v *TestSuiteMethod, _ int) bool {
				return v.IsFocused()
			})
			v.th.TestCases = unfocused
			if len(focused) > 0 {
				v.th.TestCases = focused
				skippedTestCases[v] = append(skippedTestCases[v], unfocused...)
			}

			// split excluded from included
			excluded, included := slices.SplitBy(v.th.TestCases, func(v *TestSuiteMethod, _ int) bool {
				return v.IsExcluded()
			})
			v.th.TestCases = included
			if len(excluded) > 0 {
				skippedTestCases[v] = append(skippedTestCases[v], excluded...)
			}
		})
	}

	return effectiveSet, skippedTestSuites, skippedTestCases
}

type TestSuiteSpec struct {
	pkg                *packages.Package
	n                  ast.Node
	ts                 *ast.TypeSpec
	typ                *types.Struct
	underlyingTypeName string // non-empty for aliases of generic types (e.g. "GenericTestSuite")
	th                 *TestSuiteHarness
	fixture            *FixtureSpec
	fixtureFieldName   string // field name used in the suite struct to hold the fixture pointer
}

// Identifier returns the Types Name.
//
// FOR RENDERING
func (ts *TestSuiteSpec) PackageName() string {
	return ts.pkg.Name
}

// Identifier returns the Types Name.
//
// FOR RENDERING
func (ts *TestSuiteSpec) Identifier() string {
	return ts.ts.Name.Name
}

// StructType returns the underlying *types.Struct for field inspection.
func (ts *TestSuiteSpec) StructType() *types.Struct { return ts.typ }

// Fixture returns the fixture spec embedded in this test suite, or nil.
//
// FOR RENDERING
func (ts *TestSuiteSpec) Fixture() *FixtureSpec { return ts.fixture }

// SetFixture sets the fixture spec for this test suite.
func (ts *TestSuiteSpec) SetFixture(f *FixtureSpec) { ts.fixture = f }

// FixtureFieldName returns the field name used in the suite struct for the fixture pointer.
func (ts *TestSuiteSpec) FixtureFieldName() string { return ts.fixtureFieldName }

// SetFixtureFieldName sets the field name used in the suite struct for the fixture pointer.
func (ts *TestSuiteSpec) SetFixtureFieldName(name string) { ts.fixtureFieldName = name }

// FullIdentifier returns the Types Name plus it's package identifier with dot-notation.
//
// FOR RENDERING
func (ts *TestSuiteSpec) FullIdentifier() string {
	if ts.IsPxTestSuite() {
		return ts.Identifier()
	}
	return ts.pkg.Name + "." + ts.Identifier()
}

// IsPxTestSuite gives info about the test suites declarated package.
//
// FOR RENDERING
func (ts *TestSuiteSpec) IsPxTestSuite() bool {
	return strings.HasSuffix(ts.pkg.Name, "_test")
}

// BeforeAll returns the method pointer.
//
// FOR RENDERING
func (ts *TestSuiteSpec) BeforeAll() *TestSuiteMethod {
	return ts.th.BeforeAll
}

// AfterAll returns the method pointer.
//
// FOR RENDERING
func (ts *TestSuiteSpec) AfterAll() *TestSuiteMethod {
	return ts.th.AfterAll
}

// BeforeEach returns the method pointer.
//
// FOR RENDERING
func (ts *TestSuiteSpec) BeforeEach() *TestSuiteMethod {
	return ts.th.BeforeEach
}

// AfterEach returns the method pointer.
//
// FOR RENDERING
func (ts *TestSuiteSpec) AfterEach() *TestSuiteMethod {
	return ts.th.AfterEach
}

// TestCases returns the sequential test cases slice.
//
// FOR RENDERING
func (ts *TestSuiteSpec) TestCases() []*TestSuiteMethod {
	return ts.th.TestCases
}

// HasConfig returns true when the suite defines a SuiteConfig() marker method.
//
// FOR RENDERING
func (ts *TestSuiteSpec) HasConfig() bool { return ts.th.Config != nil }

// HasGuard returns true when the suite defines a SuiteGuard() marker method.
//
// FOR RENDERING
func (ts *TestSuiteSpec) HasGuard() bool { return ts.th.Guard != nil }

// IsMethodParallel returns true when SuiteConfig has Parallel: true.
//
// FOR RENDERING
func (ts *TestSuiteSpec) IsMethodParallel() bool { return ts.th.ConfigParallel }

// HasReturningBeforeEach returns true when BeforeEach is defined and returns a context value.
//
// FOR RENDERING
func (ts *TestSuiteSpec) HasReturningBeforeEach() bool {
	return ts.th.BeforeEach != nil && ts.th.BeforeEach.HasReturn()
}

// ContextTypeName returns the rendered type name of the BeforeEach return type.
//
// FOR RENDERING
func (ts *TestSuiteSpec) ContextTypeName() string {
	if !ts.HasReturningBeforeEach() {
		return ""
	}
	return ts.th.BeforeEach.ReturnTypeName(ts.pkg.Types)
}

// ContextTypePkgPath returns the import path of the package containing the context type,
// or empty string if the type is in the same package.
//
// FOR RENDERING
func (ts *TestSuiteSpec) ContextTypePkgPath() string {
	if !ts.HasReturningBeforeEach() {
		return ""
	}
	rt := ts.th.BeforeEach.returnType
	ptr, ok := rt.(*types.Pointer)
	if !ok {
		return ""
	}
	named, ok := ptr.Elem().(*types.Named)
	if !ok {
		return ""
	}
	p := named.Obj().Pkg()
	if p == nil || p == ts.pkg.Types {
		return ""
	}
	return p.Path()
}

func (ts *TestSuiteSpec) FileSet() *token.FileSet { return ts.pkg.Fset }
func (ts *TestSuiteSpec) Pos() token.Pos           { return ts.ts.Name.Pos() }
func (ts *TestSuiteSpec) IsFocused() bool           { return strings.HasPrefix(ts.ts.Name.Name, "F_") }
func (ts *TestSuiteSpec) IsExcluded() bool          { return strings.HasPrefix(ts.ts.Name.Name, "X_") }

// TypeSpecPos returns the token position of the test suite type name.
func (ts *TestSuiteSpec) TypeSpecPos() token.Pos {
	return ts.ts.Name.Pos()
}

// Package returns the underlying *packages.Package.
func (ts *TestSuiteSpec) Package() *packages.Package {
	return ts.pkg
}

type TestSuiteHarness struct {
	BeforeAll        *TestSuiteMethod
	BeforeEach       *TestSuiteMethod
	AfterAll         *TestSuiteMethod
	AfterEach        *TestSuiteMethod
	TestCases        []*TestSuiteMethod
	Config           *types.Func // SuiteConfig() method, may be nil
	Guard            *types.Func // SuiteGuard() method, may be nil
	ConfigParallel bool
}

type TestSuiteMethod struct {
	n            ast.Node
	m            *types.Func
	sig          *types.Signature
	usesStdlibT  bool
	contextParam *types.Var // non-nil if method has a context parameter (2nd param)
	returnType   types.Type // non-nil if method returns a value (BeforeEach only)
}

// UsesStdlibT returns true if the method's parameter is *testing.T instead of *gotest.T.
func (m *TestSuiteMethod) UsesStdlibT() bool { return m.usesStdlibT }

func (m *TestSuiteMethod) HasContextParam() bool { return m.contextParam != nil }
func (m *TestSuiteMethod) HasReturn() bool       { return m.returnType != nil }

func (m *TestSuiteMethod) ContextTypeName(pkg *types.Package) string {
	if m.contextParam == nil {
		return ""
	}
	return types.TypeString(m.contextParam.Type(), qualifier(pkg))
}

func (m *TestSuiteMethod) ReturnTypeName(pkg *types.Package) string {
	if m.returnType == nil {
		return ""
	}
	return types.TypeString(m.returnType, qualifier(pkg))
}

func qualifier(pkg *types.Package) types.Qualifier {
	return func(other *types.Package) string {
		if other == pkg {
			return ""
		}
		return other.Name()
	}
}

func (m *TestSuiteMethod) Pos() token.Pos  { return m.n.Pos() }
func (m *TestSuiteMethod) IsFocused() bool  { return strings.HasPrefix(m.m.Name(), "F_") }
func (m *TestSuiteMethod) IsExcluded() bool { return strings.HasPrefix(m.m.Name(), "X_") }

// Identifier returns the test methods identifier.
//
// FOR RENDERING
func (m *TestSuiteMethod) Identifier() string {
	return m.m.Name()
}

func parseSuiteConfigAST(_ *packages.Package, funcDecl *ast.FuncDecl) (parallel bool, err error) {
	if funcDecl.Body == nil || len(funcDecl.Body.List) != 1 {
		return false, fmt.Errorf("SuiteConfig method body must be a single return statement with a gotest.SuiteConfig struct literal")
	}
	retStmt, ok := funcDecl.Body.List[0].(*ast.ReturnStmt)
	if !ok || len(retStmt.Results) != 1 {
		return false, fmt.Errorf("SuiteConfig method body must be a single return statement with a gotest.SuiteConfig struct literal")
	}
	switch result := retStmt.Results[0].(type) {
	case *ast.CompositeLit:
		for _, elt := range result.Elts {
			kv, ok := elt.(*ast.KeyValueExpr)
			if !ok {
				continue
			}
			key, ok := kv.Key.(*ast.Ident)
			if !ok {
				continue
			}
			if key.Name == "Parallel" {
				ident, ok := kv.Value.(*ast.Ident)
				if ok && ident.Name == "true" {
					parallel = true
				}
			}
		}
		return parallel, nil
	case *ast.CallExpr:
		return false, nil
	case *ast.Ident:
		return false, fmt.Errorf("SuiteConfig method body must be a single return statement with a gotest.SuiteConfig struct literal")
	default:
		return false, fmt.Errorf("SuiteConfig method body must be a single return statement with a gotest.SuiteConfig struct literal")
	}
}

func DetermineTestSuite(n ast.Node, pkg *packages.Package) (*TestSuiteSpec, token.Pos, error) {
	decl, ok := n.(*ast.GenDecl)
	if !ok || decl.Tok != token.TYPE {
		// we only care about type declarations
		return nil, -1, nil
	}

	// assert underlying enum type
	if len(decl.Specs) != 1 {
		// hint: we don't want blocks of type declarations for test suites
		return nil, -1, nil // not a test suite
	}
	ts, ok := decl.Specs[0].(*ast.TypeSpec)
	if !ok {
		return nil, -1, nil // not a test suite
	}

	if !IS_TEST_SUITE.MatchString(ts.Name.Name) {
		return nil, -1, nil // not a test suite
	}

	if ts.TypeParams != nil && ts.TypeParams.NumFields() > 0 {
		return nil, -1, nil // generic definitions are not generation targets; their aliases are
	}

	var typ *types.Struct
	var underlyingTypeName string
	rawType := pkg.TypesInfo.TypeOf(ts.Type)
	if t, ok := rawType.(*types.Struct); ok {
		typ = t
	} else if named, ok := rawType.(*types.Named); ok {
		if t, ok := named.Underlying().(*types.Struct); ok {
			typ = t
			underlyingTypeName = named.Obj().Name()
		}
	}
	if typ == nil {
		return nil, -1, nil
	}

	return &TestSuiteSpec{pkg: pkg, n: n, ts: ts, typ: typ, underlyingTypeName: underlyingTypeName, th: &TestSuiteHarness{}}, -1, nil
}

func DetermineTestSuiteHarness(n ast.Node, pkg *packages.Package, s *TestSuiteSpec) (token.Pos, error) {
	decl, ok := n.(*ast.FuncDecl)
	if !ok {
		// we only care about method declarations
		return -1, nil
	}
	if !decl.Name.IsExported() {
		return -1, nil
	}
	m, ok := pkg.TypesInfo.ObjectOf(decl.Name).(*types.Func)
	if !ok {
		return -1, nil
	}
	// methodID is a readable name, e.g. "MyTestSuite.BeforeAll" for improved debug output
	methodID := s.ts.Name.Name + "." + m.Name()

	if ok := IS_TEST_SUITE_METHOD.MatchString(m.Name()); !ok {
		return -1, nil
	}

	sig, ok := pkg.TypesInfo.TypeOf(decl.Name).(*types.Signature)
	if !ok {
		return -1, nil
	}
	recv := sig.Recv()
	if recv == nil {
		return -1, nil
	}
	{ // test for non-pointer suite receivers.
		// usage of value type receivers for test-suites is discouraged.
		namedRecvr, ok := recv.Type().(*types.Named)
		if ok {
			str := namedRecvr.Obj().Name()
			if IS_TEST_SUITE.MatchString(str) { // no receiver
				return decl.Name.Pos(), fmt.Errorf("signature of %q has unsupported value type receiver", decl.Name)
			}
			return -1, nil
		}
	}
	recvPtr, ok := recv.Type().(*types.Pointer)
	if !ok {
		return -1, nil
	}

	recvType := recvPtr.Elem().(*types.Named)
	if recvType == nil {
		return decl.Name.Pos(), nil
	}
	recvName := recvType.Obj().Name()
	if recvName != s.ts.Name.Name && (s.underlyingTypeName == "" || recvName != s.underlyingTypeName) {
		return decl.Name.Pos(), nil
	}

	if m.Name() == "SuiteConfig" {
		if sig.Params().Len() != 0 || sig.Results().Len() != 1 {
			return m.Pos(), fmt.Errorf("unsupported signature for %q: expected () gotest.SuiteConfig", methodID)
		}
		resType := sig.Results().At(0).Type().String()
		if !strings.HasSuffix(resType, "/gotest.SuiteConfig") {
			return m.Pos(), fmt.Errorf("unsupported return type for %q: expected gotest.SuiteConfig, got %s", methodID, resType)
		}
		s.th.Config = m
		parallel, err := parseSuiteConfigAST(pkg, decl)
		if err != nil {
			return m.Pos(), fmt.Errorf("%s.SuiteConfig: %w", s.ts.Name.Name, err)
		}
		s.th.ConfigParallel = parallel
		return -1, nil
	}

	if m.Name() == "SuiteGuard" {
		if sig.Params().Len() != 0 || sig.Results().Len() != 1 {
			return m.Pos(), fmt.Errorf("unsupported signature for %q: expected () string", methodID)
		}
		resType := sig.Results().At(0).Type().String()
		if resType != "string" {
			return m.Pos(), fmt.Errorf("unsupported return type for %q: expected string, got %s", methodID, resType)
		}
		s.th.Guard = m
		return -1, nil
	}

	tm := &TestSuiteMethod{n: n, m: m, sig: sig}

	isTestCase := IS_TEST_CASE.MatchString(m.Name())
	switch {
	case IS_BEFORE_ALL.MatchString(m.Name()):
		s.th.BeforeAll = tm
	case IS_AFTER_ALL.MatchString(m.Name()):
		s.th.AfterAll = tm
	case IS_BEFORE_EACH.MatchString(m.Name()):
		s.th.BeforeEach = tm
	case IS_AFTER_EACH.MatchString(m.Name()):
		s.th.AfterEach = tm
	case isTestCase:
		// pass-through: these will be handled further down the line
	default:
		return decl.Name.Pos(), fmt.Errorf("detected unhandled test suite method %q", methodID)
	}

	detectParamT := func(sig *types.Signature) (usesStdlib bool, err error) {
		pT := sig.Params().At(0).Type().String()
		switch {
		case pT == "*testing.T":
			return true, nil
		case strings.HasPrefix(pT, "*"+about.Repo) && strings.HasSuffix(pT, "/gotest.T"):
			return false, nil
		default:
			return false, fmt.Errorf("unsupported param type for signature of %q: must be *gotest.T or *testing.T", methodID)
		}
	}

	if !isTestCase {
		if IS_BEFORE_EACH.MatchString(m.Name()) {
			if sig.Params().Len() != 1 {
				return m.Pos(), fmt.Errorf("unsupported signature for %q: expected exactly 1 parameter", methodID)
			}
			if sig.Results().Len() > 1 {
				return m.Pos(), fmt.Errorf("unsupported signature for %q: expected 0 or 1 return values, got %d", methodID, sig.Results().Len())
			}
			usesStdlib, err := detectParamT(sig)
			if err != nil {
				return m.Pos(), err
			}
			tm.usesStdlibT = usesStdlib
			if sig.Results().Len() == 1 {
				tm.returnType = sig.Results().At(0).Type()
			}
			return -1, nil
		}

		if IS_AFTER_EACH.MatchString(m.Name()) {
			if sig.Params().Len() < 1 || sig.Params().Len() > 2 || sig.Results().Len() != 0 {
				return m.Pos(), fmt.Errorf("unsupported signature for %q: expected 1 or 2 parameters and no return values", methodID)
			}
			usesStdlib, err := detectParamT(sig)
			if err != nil {
				return m.Pos(), err
			}
			tm.usesStdlibT = usesStdlib
			if sig.Params().Len() == 2 {
				tm.contextParam = sig.Params().At(1)
			}
			return -1, nil
		}

		// BeforeAll, AfterAll — unchanged: exactly 1 param, 0 return values
		if sig.Params().Len() != 1 || sig.Results().Len() != 0 {
			return m.Pos(), fmt.Errorf("unsupported signature for %q", methodID)
		}
		usesStdlib, err := detectParamT(sig)
		if err != nil {
			return m.Pos(), err
		}
		tm.usesStdlibT = usesStdlib
		return -1, nil
	}

	s.th.TestCases = append(s.th.TestCases, tm)

	maxParams := 1

	// optional context parameter (second position, before optional done func())
	if sig.Params().Len() >= 2 {
		secondParam := sig.Params().At(1)
		secondType := secondParam.Type().String()
		if secondType != "func()" {
			tm.contextParam = secondParam
			maxParams += 1
		}
	}

	// end with `done func()` IF test case IS ASYNC
	if IS_TEST_CASE_ASYNC.MatchString(m.Name()) {
		lastParam := sig.Params().At(sig.Params().Len() - 1)
		if lastParam.String() != "var done func()" {
			return lastParam.Pos(), fmt.Errorf("unsupported last argument for %q", methodID)
		}
		maxParams += 1
	}

	if sig.Params().Len() != maxParams {
		return m.Pos(), fmt.Errorf("unsupported number of params for signature of %q", methodID)
	}

	usesStdlib, err := detectParamT(sig)
	if err != nil {
		return m.Pos(), err
	}
	tm.usesStdlibT = usesStdlib

	return -1, nil
}

// ValidateContextConsistency checks that all methods in the suite agree on whether
// they accept a context parameter, and that context types match BeforeEach's return type.
func ValidateContextConsistency(ts *TestSuiteSpec) error {
	be := ts.th.BeforeEach
	ae := ts.th.AfterEach
	suiteName := ts.ts.Name.Name

	// Rule 1/7: Parallel requires returning BeforeEach (void BeforeEach forbidden)
	if ts.th.ConfigParallel && be != nil && !be.HasReturn() {
		return fmt.Errorf("%s: SuiteConfig has Parallel: true, but BeforeEach has no return value. Parallel methods require per-test isolation — move per-test fields to a context struct and return it from BeforeEach", suiteName)
	}

	if be == nil || !be.HasReturn() {
		// Void or absent BeforeEach — no methods should have context param
		for _, tc := range ts.th.TestCases {
			if tc.HasContextParam() {
				return fmt.Errorf("%s.%s: has context parameter but BeforeEach does not return a context", suiteName, tc.Identifier())
			}
		}
		// Rule 4: No orphan context AfterEach
		if ae != nil && ae.HasContextParam() {
			return fmt.Errorf("%s.AfterEach: accepts a context parameter but BeforeEach does not return one", suiteName)
		}
		return nil
	}

	// Returning BeforeEach — ALL methods must have context param
	ctxType := be.returnType.String()

	for _, tc := range ts.th.TestCases {
		if !tc.HasContextParam() {
			return fmt.Errorf("%s.%s: suite has a returning BeforeEach but this method does not accept the context parameter. All methods in a returning-BeforeEach suite must consistently include the context parameter", suiteName, tc.Identifier())
		}
		// Rule 6: Type consistency
		if tc.contextParam.Type().String() != ctxType {
			return fmt.Errorf("%s.%s: context parameter type %s does not match BeforeEach return type %s", suiteName, tc.Identifier(), tc.contextParam.Type(), be.returnType)
		}
	}

	// Rule 3: AfterEach matches BeforeEach
	if ae != nil {
		if !ae.HasContextParam() {
			return fmt.Errorf("%s.AfterEach: suite has a returning BeforeEach but AfterEach does not accept the context. Add the context as the second parameter", suiteName)
		}
		if ae.contextParam.Type().String() != ctxType {
			return fmt.Errorf("%s.AfterEach: context type %s does not match BeforeEach return type %s", suiteName, ae.contextParam.Type(), be.returnType)
		}
	}

	return nil
}
