package gotestast_test

import (
	"go/ast"
	"go/parser"
	"go/token"

	"github.com/mvrahden/go-test/internal/gotestast"
	"github.com/mvrahden/go-test/pkg/gotest"
)

type TestMainTestSuite struct{}

func (s *TestMainTestSuite) SuiteConfig() gotest.SuiteConfig {
	cfg := gotest.DefaultSuiteConfig()
	cfg.Parallel = true
	return cfg
}

func parseFiles(t *gotest.T, srcs ...string) (*token.FileSet, []*ast.File) {
	return parseNamed(t, "x_test.go", srcs...)
}

func parseNamed(t *gotest.T, name string, srcs ...string) (*token.FileSet, []*ast.File) {
	fset := token.NewFileSet()
	files := make([]*ast.File, 0, len(srcs))
	for _, src := range srcs {
		f, err := parser.ParseFile(fset, name, src, parser.ParseComments)
		gotest.NoError(t, err)
		files = append(files, f)
	}
	return fset, files
}

func (s *TestMainTestSuite) TestRoutesThroughRuntime(t *gotest.T) {
	for t, tc := range gotest.Each(t, []struct {
		Desc string
		src  string
		want bool
	}{
		{"the runtime under its own name", `package p
import ("os"; "testing"; "github.com/mvrahden/go-test/pkg/gotestruntime")
func TestMain(m *testing.M) { os.Exit(gotestruntime.Main(m)) }`, true},
		{"the runtime under an alias", `package p
import ("os"; "testing"; rt "github.com/mvrahden/go-test/pkg/gotestruntime")
func TestMain(m *testing.M) { code := rt.Main(m); os.Exit(code) }`, true},
		{"the wrapper, handed to a library", `package p
import ("testing"; "github.com/mvrahden/go-test/pkg/gotestruntime")
func verify(m interface{ Run() int }) {}
func TestMain(m *testing.M) { verify(gotestruntime.M(m)) }`, true},
		{"the runtime dot-imported", `package p
import ("os"; "testing"; . "github.com/mvrahden/go-test/pkg/gotestruntime")
func TestMain(m *testing.M) { os.Exit(Main(m)) }`, true},
		{"the runtime blank-imported, m.Run called", `package p
import ("os"; "testing"; _ "github.com/mvrahden/go-test/pkg/gotestruntime")
func TestMain(m *testing.M) { os.Exit(m.Run()) }`, false},
		{"m.Run", `package p
import ("os"; "testing")
func TestMain(m *testing.M) { os.Exit(m.Run()) }`, false},
		{"another package's Main", `package p
import ("os"; "testing"; gotestruntime "example.com/other")
func TestMain(m *testing.M) { os.Exit(gotestruntime.Main(m)) }`, false},
	}) {
		fd, f := gotestast.FindTestMain(parseFiles(t, tc.src))
		gotest.NotZero(t, fd)
		gotest.Equal(t, tc.want, gotestast.RoutesThroughRuntime(f, fd))
	}
}

func (s *TestMainTestSuite) TestFindTestMain(t *gotest.T) {
	t.When("only a harness gotest generated declares one", func(w *gotest.T) {
		w.It("finds none: the developer wrote no TestMain", func(it *gotest.T) {
			fd, _ := gotestast.FindTestMain(parseFiles(it, `// Code generated by "gotest (github.com/mvrahden/go-test)"; DO NOT EDIT.

package p
import "testing"
func TestMain(m *testing.M) {}`))
			gotest.Zero(it, fd)
		})
	})

	t.When("another generator wrote the file", func(w *gotest.T) {
		w.It("finds it: go test runs it as the TestMain", func(it *gotest.T) {
			fd, _ := gotestast.FindTestMain(parseFiles(it, `// Code generated by mockgen. DO NOT EDIT.

package p
import "testing"
func TestMain(m *testing.M) {}`))
			gotest.NotZero(it, fd)
		})
	})

	t.When("the TestMain is in a file that is not a test file", func(w *gotest.T) {
		w.It("finds none: go test does not run it", func(it *gotest.T) {
			fd, _ := gotestast.FindTestMain(parseNamed(it, "prod.go", `package p
import "testing"
func TestMain(m *testing.M) {}`))
			gotest.Zero(it, fd)
		})
	})

	t.When("TestMain takes something other than *testing.M", func(w *gotest.T) {
		w.It("finds none: it is an ordinary test", func(it *gotest.T) {
			fd, _ := gotestast.FindTestMain(parseFiles(it, `package p
import "testing"
func TestMain(t *testing.T) {}`))
			gotest.Zero(it, fd)
		})
	})

	t.When("a method is named TestMain", func(w *gotest.T) {
		w.It("finds none", func(it *gotest.T) {
			fd, _ := gotestast.FindTestMain(parseFiles(it, `package p
type S struct{}
func (S) TestMain() {}`))
			gotest.Zero(it, fd)
		})
	})
}
